DROP TABLE peliculas;

CREATE TABLE peliculas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    anio NUMBER(4) NOT NULL CHECK (anio >= 1888), -- La primera película fue en 1888
    director VARCHAR2(60) NOT NULL,
    genero VARCHAR2(100) NOT NULL,
    sinopsis VARCHAR2(255)
); 

INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('El Padrino', 1972, 'Francis Ford Coppola', 'Crimen/Drama', 'La historia de la familia criminal Corleone.');
INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('Interestelar', 2014, 'Christopher Nolan', 'Ciencia ficción', 'Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.');
INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('Parásitos', 2019, 'Bong Joon-ho', 'Thriller/Drama', 'Una familia pobre se infiltra en la vida de una familia rica con consecuencias inesperadas.');
INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('El Señor de los Anillos: El Retorno del Rey', 2003, 'Peter Jackson', 'Fantasía/Aventura', 'La batalla final por la Tierra Media y el destino del Anillo Único.');
INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('Titanic', 1997, 'James Cameron', 'Romance/Drama', 'La historia de amor de Jack y Rose en el trágico viaje del Titanic.');
INSERT INTO peliculas (titulo, anio, director, genero, sinopsis) VALUES
('El Caballero de la Noche', 2008, 'Christopher Nolan', 'Acción/Crimen', 'Batman enfrenta al Joker en una lucha por el alma de Gotham.');